name: Deploy site to GitHub Pages

on:
  # Run on pushes to the default branch
  push:
    branches: [master]
  # Allow manual runs from the Actions tab
  workflow_dispatch:

# Allow this job to deploy to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install, build, and upload the site
        uses: withastro/action@v3
        # with:
        #   path: .            # root location of the Astro project
        #   node-version: 20   # defaults to 20
        #   package-manager: npm

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
